services:
  # Our database management system
  db:
    environment:
      MARIADB_USER: &dbuser todo
      MARIADB_PASSWORD: &dbpass todosecret
      MARIADB_ROOT_PASSWORD: iamroot
      MARIADB_DATABASE: &dbname videos

  # Our microservices, built with './gradlew dockerBuild'
  video:
    environment:
      DB_USER: *dbuser
      DB_PASSWORD: *dbpass
      DB_NAME: *dbname

  subscription:
    environment:
      DB_USER: *dbuser
      DB_PASSWORD: *dbpass
      DB_NAME: subscriptions
  
  trending:
    environment:
      DB_USER: *dbuser
      DB_PASSWORD: *dbpass
      DB_NAME: trending
